version: 2.1

orbs:
  hello-but-actually-ias: circleci/hello-build@0.0.13
  ias-stuff:
    commands:
      hello-ias:
        steps:
          - run: echo "Hello, IAS orb"
      goodbye-ias:
        steps:
          - run: echo "Goobye, IAS orb"
  jq: circleci/jq@1.6.1
commands:
  hello-ias:
    steps:
      - run: echo "Hello, IAS command"
  goodbye-ias:
    steps:
      - run: echo "Goobye, IAS command"
jobs:
  my-ias-job:
    executor: hello-but-actually-ias/default # Kick this off with <whatever hello-build/default says> container
    steps:
    - run: echo "Hello, IAS; gonna install jq"
    - jq/install
    - run: |
        echo '{"foo": "bar"}' | jq .
    - run: echo "Goobye, IAS"

workflows:
  hello-ias-workflow:
    jobs:
    - my-ias-job
